"""report_to_pdf.py — regression suite for the authored-report PDF pipeline.

This tool owns the mandatory "Evidence basis & confidence" banner
(__file_meta__ rule ``keep-disclaimer``, severity error) yet had no dedicated
tests. Contracts pinned here:

- a report with disclaimer frontmatter renders to a real PDF, and the
  intermediate HTML carries the banner, the notice, confidence pills,
  callouts, and vector charts;
- a report WITHOUT disclaimer frontmatter is refused with an actionable
  message — the banner is required output, silent omission was the defect;
- the banner label defaults to the shared phrase and honors an explicit
  operator override;
- authoring primitives degrade gracefully (bad chart spec, unterminated
  callout) instead of killing the render or losing content.

Requires the project env (yaml, markdown-it-py, weasyprint):
run from the repo root via  uv run python -m pytest tests/test_report_to_pdf.py
"""
from __future__ import annotations

import html as _html
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

pytest.importorskip("yaml")
pytest.importorskip("markdown_it")
pytest.importorskip("weasyprint")

import report_to_pdf as R  # noqa: E402

LABEL = "Evidence basis & confidence"

GOOD_REPORT = """---
title: "Architectural Analysis — example"
subtitle: "pipeline regression fixture"
masthead:
  - Bundle: example
  - Commit: abc1234
disclaimer:
  notice: "Structural findings are mechanical; interpretations are LLM-authored and unverified."
  generated_by: "test-suite"
  date: "2026-07-09"
footer: "example report"
---

## 1. Coupling posture {confidence: low}

Body paragraph.

::: risk  Migration debt (primary risk)
Callout body with *markdown*.
:::

```chart
{"type": "hbar", "title": "Files by language", "data": [["python", 10], ["rust", 4]]}
```
"""

NO_DISCLAIMER_REPORT = """---
title: "Report without provenance"
---

## Section

Text.
"""


# ------------------------------------------------------------- end-to-end
def test_full_render_produces_pdf_and_banner(tmp_path):
    src = tmp_path / "report.md"
    src.write_text(GOOD_REPORT, encoding="utf-8")
    out = tmp_path / "report.pdf"

    rc = R.main([str(src), "-o", str(out), "--html"])

    assert rc == 0
    assert out.read_bytes()[:5] == b"%PDF-"
    html = (tmp_path / "report.html").read_text(encoding="utf-8")
    assert _html.escape(LABEL) in html                      # the banner
    assert "Structural findings are mechanical" in html     # the notice
    assert "Generated by:" in html and "test-suite" in html  # provenance
    assert 'class="confidence conf-low"' in html             # confidence pill
    assert 'class="callout risk"' in html                    # callout
    assert "<svg" in html                                    # vector chart


def test_render_without_disclaimer_is_refused(tmp_path):
    src = tmp_path / "bare.md"
    src.write_text(NO_DISCLAIMER_REPORT, encoding="utf-8")
    out = tmp_path / "bare.pdf"

    with pytest.raises(SystemExit) as exc:
        R.main([str(src), "-o", str(out)])

    msg = str(exc.value)
    assert "disclaimer" in msg
    assert "_report_template.md" in msg  # actionable: points at the template
    assert not out.exists()              # nothing rendered silently


# ------------------------------------------------------------- banner unit
def test_disclaimer_label_defaults_to_shared_phrase():
    banner = R.build_disclaimer({"disclaimer": {"notice": "n"}})
    assert _html.escape(LABEL) in banner


def test_disclaimer_label_honors_operator_override():
    banner = R.build_disclaimer(
        {"disclaimer": {"notice": "n", "label": "Custom label"}})
    assert "Custom label" in banner
    assert _html.escape(LABEL) not in banner


def test_empty_notice_yields_no_banner():
    assert R.build_disclaimer({}) == ""
    assert R.build_disclaimer({"disclaimer": {"notice": "  "}}) == ""


# ------------------------------------------------------- authoring primitives
@pytest.mark.parametrize("line,expected_class", [
    ("## Title {confidence: low}", "conf-low"),
    ("## Title {confidence: HIGH}", "conf-high"),
    ("## Title {confidence: bogus}", "conf-medium"),  # unknown -> medium
])
def test_tag_confidence_levels(line, expected_class):
    assert expected_class in R._tag_confidence(line)


def test_tag_confidence_leaves_plain_lines_alone():
    assert R._tag_confidence("plain prose {confidence: low}") \
        == "plain prose {confidence: low}"
    assert R._tag_confidence("## no tag here") == "## no tag here"


def test_parse_blocks_segments_callouts():
    blocks = R.parse_blocks(
        "before\n::: note  A title\ninner\n:::\nafter")
    kinds = [b["kind"] for b in blocks]
    assert kinds == ["md", "callout", "md"]
    assert blocks[1]["type"] == "note"
    assert blocks[1]["title"] == "A title"
    assert blocks[1]["text"] == "inner"


def test_unterminated_callout_content_is_not_lost():
    blocks = R.parse_blocks("::: risk  Oops\nline kept")
    assert len(blocks) == 1 and blocks[0]["kind"] == "md"
    assert "line kept" in blocks[0]["text"]


def test_bad_chart_spec_degrades_to_error_callout():
    out = R.render_chart_block("not json at all")
    assert "Chart render error" in out
    assert "<svg" not in out


def test_unknown_chart_type_is_disclosed():
    out = R.render_chart_block('{"type": "pie3d", "data": []}')
    assert "Unknown chart type" in out


def test_page_css_escapes_footer_quotes():
    css = R.page_css({"footer": 'he said "hi"'})
    assert '\\"hi\\"' in css
