#!/usr/bin/env python3
"""verify_regenerate.py — end-to-end contract for the TTL+AST regenerate path.

Drives the new ``regenerate`` API: read inventory.ttl alone (no blobs) and
re-materialize source via per-language regenerators. Python regenerates
*semantically* (re-parses to the same AST); TS/JS regenerate
*byte-identically* via the stored leaf-text CST.

Tests:
  1. Every supported file is regenerated; per-language ok/failed counts
     match the fixture composition.
  2. Python files: regenerated source re-parses to the same AST as the
     original (``ast.dump`` equality).
  3. TS/JS files: regenerated bytes match the original byte-for-byte, and
     sha256 of the output equals the inventory's cbm:contentSha256.
  4. Files of unsupported language (markdown/binary/empty) are reported in
     ``ast_unsupported``/``no_ast_summary`` and not written to disk.
  5. Mutation: corrupting cbm:astSummary literal (invalid JSON) lands in
     ``ast_parse_errors`` and does not poison other files.
  6. Mutation: deleting cbm:astSummary triple lands in ``no_ast_summary``.
  7. Mutation: changing cbm:language to a foreign value lands in
     ``ast_unsupported``.
  8. CLI parity: ``python -m codebase_mapper --regenerate --inventory I
     --out O --report R`` exits 0, writes the report, and regenerates the
     expected files.

Exit code: 0 if all pass, 1 otherwise.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from rdflib import Graph, Literal, URIRef
from rdflib.namespace import RDF

from codebase_mapper.shared_kernel.constants import CBM, CBMI_NS
from codebase_mapper.inspection.pipeline import map_codebase
from codebase_mapper.emission.infrastructure.rdf.rdflib_emitter import build_inventory_graph
from codebase_mapper.emission.application.regenerate import regenerate


PASS = 0
FAIL = 0


def check(name: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        print(f"  PASS  {name}")
        PASS += 1
    else:
        print(f"  FAIL  {name}")
        if detail:
            for line in detail.splitlines()[:12]:
                print(f"        {line}")
        FAIL += 1


PY_KITCHEN_SINK = '''"""module docstring."""
import json
from dataclasses import dataclass, field
from collections.abc import Iterable as _Iter

CONST = 42
PI = 3.14159
RAW = b"\\x00\\xff hi"


@dataclass
class User:
    """class docstring."""
    name: str
    age: int = 0
    tags: list[str] = field(default_factory=list)

    def greet(self, prefix: str = "hi", *, loud: bool = False) -> str:
        """method docstring."""
        msg = f"{prefix}, {self.name}!"
        return msg.upper() if loud else msg

    async def fetch(self) -> dict[str, int]:
        return {self.name: self.age}


def add(a: int, b: int = 1, *args: int, **kwargs: int) -> int:
    """sum."""
    total = a + b + sum(args)
    for k, v in kwargs.items():
        total += len(k) + v
    return total


try:
    x = add(1, 2, 3, foo=4)
except (TypeError, ValueError) as e:
    print(e)
finally:
    pass


squares = [i * i for i in range(10) if i % 2]
mapping = {a: b for a, b in zip([1, 2], [3, 4])}


match x:
    case 0:
        y = "zero"
    case [a, *rest]:
        y = a
    case {"k": v}:
        y = v
    case _:
        y = None

assert True, "ok"
'''

PY_SIMPLE = '''"""tiny module."""

def hi():
    return "hi"
'''

TS_SRC = (
    "// leading comment\n"
    'import { readFile } from "fs/promises";\n'
    'import type { Foo } from "./foo";\n'
    "\n"
    "/** loader docstring */\n"
    "export async function loadConfig<T extends object>(\n"
    "    path: string,\n"
    "    opts: { strict?: boolean } = {},\n"
    "): Promise<T> {\n"
    '    const raw = await readFile(path, "utf-8");\n'
    "    if (opts.strict && !raw.length) {\n"
    '        throw new Error(`empty: ${path}`);  // trailing comment\n'
    "    }\n"
    "    return JSON.parse(raw) as T;\n"
    "}\n"
    "\n"
    "export class Box<T> {\n"
    "    private value: T;\n"
    "    constructor(v: T) { this.value = v; }\n"
    "    get(): T { return this.value; }\n"
    "}\n"
)

JS_SRC = (
    'const path = require("path");\n'
    "\n"
    "function add(a, b) {\n"
    "    return a + b;\n"
    "}\n"
    "\n"
    "module.exports = { add };\n"
)


def build_fixture(target: Path) -> None:
    target.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=target, check=True)
    subprocess.run(["git", "-C", str(target), "config", "user.email", "t@t"], check=True)
    subprocess.run(["git", "-C", str(target), "config", "user.name", "t"], check=True)

    (target / "app.py").write_text(PY_KITCHEN_SINK)
    (target / "lib.py").write_text(PY_SIMPLE)
    (target / "utils.ts").write_text(TS_SRC)
    (target / "helper.js").write_text(JS_SRC)
    (target / "README.md").write_text("# fixture\n")
    (target / "empty.txt").write_text("")
    (target / "asset.bin").write_bytes(b"\x89PNG\r\n\x00\x01\x02\xff\xfe")

    subprocess.run(["git", "-C", str(target), "add", "-A"], check=True)
    subprocess.run(
        ["git", "-C", str(target), "commit", "-q", "-m", "init"], check=True
    )


def emit_inventory_only(repo: Path, out_dir: Path) -> dict:
    """Write inventory.ttl. No blobs, no SHACL, no manifest — minimal."""
    mapped = map_codebase(repo, "HEAD")
    inv = build_inventory_graph(
        repo_iri=URIRef(f"{CBMI_NS}repo/{repo.name}"),
        commit_sha=mapped["commit"],
        records=mapped["records"],
        import_edges=mapped["import_edges"],
        import_ext_edges=mapped["import_ext_edges"],
        dep_edges=mapped["dep_edges"],
        pin_edges=mapped["pin_edges"],
        tests_edges=mapped["tests_edges"],
    )
    inv.serialize(destination=str(out_dir / "inventory.ttl"), format="turtle")
    return mapped


def main(argv: list[str] | None = None) -> int:
    global PASS, FAIL
    p = argparse.ArgumentParser()
    p.add_argument("--keep", action="store_true", help="don't delete the workdir on exit")
    args = p.parse_args(argv)

    work = Path(tempfile.mkdtemp(prefix="verify_regenerate_"))
    try:
        fixture = work / "fixture"
        build_fixture(fixture)
        repo_root = Path(__file__).resolve().parent.parent

        # --- Emit inventory.ttl (no blobs) ---
        emit_dir = work / "emit"
        emit_dir.mkdir()
        mapped = emit_inventory_only(fixture.resolve(), emit_dir)
        inv_path = emit_dir / "inventory.ttl"

        regen_langs = {"python", "typescript", "javascript"}
        regen_records = [r for r in mapped["records"] if r.language in regen_langs]
        skipped_records = [r for r in mapped["records"] if r.language not in regen_langs]
        py_paths = [r.path for r in regen_records if r.language == "python"]
        ts_paths = [r.path for r in regen_records if r.language == "typescript"]
        js_paths = [r.path for r in regen_records if r.language == "javascript"]
        check(
            "fixture has Python + TypeScript + JavaScript + unsupported files",
            len(py_paths) >= 2 and len(ts_paths) >= 1 and len(js_paths) >= 1
            and len(skipped_records) >= 1,
            f"py={py_paths} ts={ts_paths} js={js_paths} "
            f"skipped={[r.path for r in skipped_records]}",
        )

        # --- 1. Regenerate; assert per-language counts ---
        out_dir = work / "regen"
        report = regenerate(inv_path, out_dir)

        by_lang_expected = {
            "python": len(py_paths),
            "typescript": len(ts_paths),
            "javascript": len(js_paths),
        }
        check(
            "regenerate: every supported file regenerated",
            report["files_regenerated"] == len(regen_records)
            and all(
                report["by_language"].get(lang, {}).get("ok", 0) == n
                and report["by_language"].get(lang, {}).get("failed", 0) == 0
                for lang, n in by_lang_expected.items()
            ),
            json.dumps(report, indent=2, sort_keys=True),
        )

        # --- 2. Python: semantic AST equality ---
        for rec in regen_records:
            if rec.language != "python":
                continue
            orig_src = (fixture / rec.path).read_text()
            regen_src = (out_dir / rec.path).read_text()
            orig_dump = ast.dump(ast.parse(orig_src), annotate_fields=True)
            regen_dump = ast.dump(ast.parse(regen_src), annotate_fields=True)
            check(
                f"python semantic AST equality: {rec.path}",
                orig_dump == regen_dump,
                f"len orig={len(orig_dump)} regen={len(regen_dump)}",
            )

        # --- 3. TS/JS: byte equality + sha256 matches cbm:contentSha256 ---
        for rec in regen_records:
            if rec.language not in ("typescript", "javascript"):
                continue
            orig_bytes = (fixture / rec.path).read_bytes()
            regen_bytes = (out_dir / rec.path).read_bytes()
            check(
                f"{rec.language} byte equality: {rec.path}",
                regen_bytes == orig_bytes,
                f"orig_len={len(orig_bytes)} regen_len={len(regen_bytes)}; "
                f"first diff @ {next((i for i in range(min(len(orig_bytes), len(regen_bytes))) if orig_bytes[i] != regen_bytes[i]), -1)}",
            )
            check(
                f"{rec.language} sha256 matches contentSha256: {rec.path}",
                hashlib.sha256(regen_bytes).hexdigest() == rec.content_sha256,
                f"expected={rec.content_sha256} got={hashlib.sha256(regen_bytes).hexdigest()}",
            )

        # --- 4. Driver wrote each regenerated file at the correct path ---
        for rec in regen_records:
            check(
                f"regenerate writes file: {rec.path}",
                (out_dir / rec.path).is_file(),
                "missing",
            )

        # --- 5. Unsupported-language files reported and not written ---
        unsupported_paths = {d["path"] for d in report["ast_unsupported"]}
        no_ast_paths = set(report["no_ast_summary"])
        skipped_path_set = unsupported_paths | no_ast_paths
        skipped_expected = {r.path for r in skipped_records}
        check(
            "unsupported-language files reported via ast_unsupported / no_ast_summary",
            skipped_expected.issubset(skipped_path_set),
            f"expected={sorted(skipped_expected)}\n"
            f"unsupported={sorted(unsupported_paths)}\n"
            f"no_ast={sorted(no_ast_paths)}",
        )
        for p in skipped_expected:
            check(
                f"unsupported file not written to disk: {p}",
                not (out_dir / p).exists(),
                f"unexpectedly present: {out_dir / p}",
            )

        # --- 4. Mutation: corrupted ast_summary literal -> ast_parse_errors ---
        # Rewrite inventory with one Python file's astSummary set to invalid JSON,
        # then assert that file alone fails and others still regenerate.
        target_py = "app.py"
        target_iri = URIRef(f"{CBMI_NS}file/{target_py}")

        g_corrupt = Graph()
        g_corrupt.parse(str(inv_path), format="turtle")
        g_corrupt.remove((target_iri, CBM.astSummary, None))
        g_corrupt.add((target_iri, CBM.astSummary, Literal("{not json")))
        corrupt_path = work / "inventory_corrupt.ttl"
        g_corrupt.serialize(destination=str(corrupt_path), format="turtle")

        out_corrupt = work / "regen_corrupt"
        report_c = regenerate(corrupt_path, out_corrupt)
        check(
            "mutation: corrupted ast_summary -> ast_parse_errors for that file only",
            any(d["path"] == target_py for d in report_c["ast_parse_errors"])
            and report_c["by_language"].get("python", {}).get("failed", 0) == 1
            and report_c["files_regenerated"] == len(regen_records) - 1
            and not (out_corrupt / target_py).exists(),
            json.dumps(report_c, indent=2, sort_keys=True),
        )

        # --- 5. Mutation: missing ast_summary -> no_ast_summary ---
        g_missing = Graph()
        g_missing.parse(str(inv_path), format="turtle")
        g_missing.remove((target_iri, CBM.astSummary, None))
        missing_path = work / "inventory_missing.ttl"
        g_missing.serialize(destination=str(missing_path), format="turtle")

        out_missing = work / "regen_missing"
        report_m = regenerate(missing_path, out_missing)
        check(
            "mutation: missing ast_summary -> no_ast_summary for that file only",
            target_py in report_m["no_ast_summary"]
            and report_m["by_language"].get("python", {}).get("failed", 0) == 1
            and report_m["files_regenerated"] == len(regen_records) - 1,
            json.dumps(report_m, indent=2, sort_keys=True),
        )

        # --- 6. Mutation: foreign language -> ast_unsupported ---
        g_lang = Graph()
        g_lang.parse(str(inv_path), format="turtle")
        g_lang.remove((target_iri, CBM.language, None))
        g_lang.add((target_iri, CBM.language, Literal("clojure")))
        lang_path = work / "inventory_lang.ttl"
        g_lang.serialize(destination=str(lang_path), format="turtle")

        out_lang = work / "regen_lang"
        report_l = regenerate(lang_path, out_lang)
        check(
            "mutation: foreign language -> ast_unsupported, other files regenerate",
            any(d["path"] == target_py and d["language"] == "clojure"
                for d in report_l["ast_unsupported"])
            and report_l["files_regenerated"] == len(regen_records) - 1,
            json.dumps(report_l, indent=2, sort_keys=True),
        )

        # --- 7. CLI parity ---
        out_cli = work / "regen_cli"
        report_cli = work / "report_cli.json"
        cli = subprocess.run(
            [
                sys.executable, "-m", "codebase_mapper",
                "--regenerate", "--inventory", str(inv_path),
                "--out", str(out_cli), "--report", str(report_cli),
            ],
            env={**os.environ, "PYTHONPATH": str(repo_root)},
            cwd=str(repo_root),
            capture_output=True,
            text=True,
        )
        cli_report: dict = {}
        if report_cli.exists():
            try:
                cli_report = json.loads(report_cli.read_text())
            except Exception:
                pass
        check(
            "CLI: --regenerate exits 0, writes report, regenerates expected files",
            cli.returncode == 0
            and cli_report.get("files_regenerated") == len(regen_records)
            and all((out_cli / r.path).exists() for r in regen_records),
            f"rc={cli.returncode}\nstdout_tail={cli.stdout[-600:]}\nstderr_tail={cli.stderr[-600:]}",
        )

        print()
        print(f"passed: {PASS}   failed: {FAIL}")
        return 0 if FAIL == 0 else 1
    finally:
        if not args.keep:
            shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
