import { LlmEnrichment } from "../api";

/**
 * Renders an L4 enrichment as a labelled card with an "AI-enriched"
 * badge and the model+prompt provenance under a collapsible
 * <details>. The component is intentionally lightweight — provenance
 * is hidden by default so the surface tells the user "this is a model
 * output, not source-of-truth", but technical readers can expand to
 * verify the model name + prompt SHA + generation timestamp.
 *
 * Usage:
 *   <LlmEnrichmentCard label="LLM summary" enrichment={d.llm_summary} />
 *   <LlmEnrichmentCard label="LLM description" enrichment={d.llm_description} />
 *
 * Renders nothing if `enrichment` is undefined (the parent should pass
 * the field directly — caller doesn't need to guard).
 */
export default function LlmEnrichmentCard({
  label,
  enrichment,
}: {
  label: string;
  enrichment: LlmEnrichment | undefined;
}) {
  if (!enrichment) return null;
  const { text, provenance } = enrichment;
  return (
    <div
      className="card"
      data-testid="llm-enrichment-card"
      data-model={provenance.model}
    >
      <h3 style={{ display: "flex", alignItems: "center", gap: 8 }}>
        {label}
        <span
          className="tag"
          title={`Generated by ${provenance.model} at ${provenance.generated_at}`}
          style={{
            background: "#3a2645",
            color: "#e6c7f0",
            fontWeight: 600,
          }}
        >
          AI-enriched
        </span>
      </h3>
      <p style={{ marginTop: 8, lineHeight: 1.5 }}>{text}</p>
      <details style={{ marginTop: 10 }}>
        <summary
          style={{ cursor: "pointer", color: "var(--fg-dim)", fontSize: "0.85em" }}
        >
          provenance
        </summary>
        <dl className="kv" style={{ marginTop: 6, fontSize: "0.85em" }}>
          <dt>model</dt>
          <dd>{provenance.model}</dd>
          <dt>prompt sha256</dt>
          <dd style={{ fontFamily: "monospace", fontSize: "0.8em" }}>
            {provenance.prompt_sha}
          </dd>
          <dt>target sha256</dt>
          <dd style={{ fontFamily: "monospace", fontSize: "0.8em" }}>
            {provenance.target_sha}
          </dd>
          <dt>generated at</dt>
          <dd>{provenance.generated_at}</dd>
        </dl>
      </details>
    </div>
  );
}
