[pytest]
testpaths = tests
addopts =
    --cov=frontend/backend
    --cov-config=frontend/backend/.coveragerc
    --cov-report=term-missing
    --cov-fail-under=90
filterwarnings =
    ignore::DeprecationWarning:rdflib
